export const routes = {
  LOGIN: 'LoginScreen',
  SPLASH: 'SplashScreen',
  REGISTER: 'RegisterScreen',
  HOMETAB: 'HomeTabScreen',
  PROFILETAB: 'ProfieTabScreen',
  FAVORITES: 'FavoritesTabScreen',
  BASKETTAB: 'BasketTabScreen',
  RESTAURANT: 'RestaurantTabScreen',
  HOME: 'HomeStackScreen',
  DETAIL: 'DetailStackScreen',
  BASKET: 'BasketStackScreen',
  CHECKOUT: 'CheckoutStackScreen',
  DELIVERY: 'DeliveyStackScreen',
  PROFILE: 'ProfileStackScreen',
  RESTAURANTDETAIL: 'RestaurantDetailStackScreen',
};
